logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]

build-mode = "both"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = "'Custom branding'"                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "latest"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-arch = "arm-v7a"


[Messenger]

apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm-v7a"
version = "latest"

[Music]

apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm-v7a"
version = "latest"

[Tiktok]

apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
apkmirror-arch = "arm-v7a"
version = "latest"
included-patches = "'SIM spoof'"

[Reddit]

apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
apkmirror-arch = "arm-v7a"
version = "latest"

[Twitter]

apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
apkmirror-arch = "arm-v7a"
version = "beta"

[Lightroom]

apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"
version = "latest"    
  

[Spotify]

uptodown-dlurl = "https://spotify.en.uptodown.com/android"
version = "latest"    

[Backdrops]
version = "latest"    
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers/"

[Photomath]
version = "latest"    
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
